change all commands to use secrets/project file to determine project
Note: rather than depend on --project flags or global gcloud project, which seems
dangerous.

update cloudbuild-*.yaml to take out --project flags (not tested)

add project keyring / project key in init-project, but note I have a better idea
for this organization.

diff --git a/bin/add-function b/bin/add-function
--- a/bin/add-function
+++ b/bin/add-function
@@ -8,20 +8,27 @@ if [ -z "${FUNC}" ]; then
   exit 1
 fi
 
+PROJ=$(cat secrets/project)
+
+if [ -z "${PROJ}" ]; then
+    echo "Project not found. Check secrets/project file." >&2
+    exit 1
+fi
+
 echo "Creating function template..." >&2
 cd functions && \
     cookiecutter git+ssh://git@bitbucket.org/ericgj/ert-gcf-function-cookiecutter.git && \
     cd ..
 
 echo "Creating service account for function..." >&2
-gcloud iam service-accounts create "gws-noticeboard-${FUNC}" \
-    --project "gws-noticeboard"
+gcloud iam service-accounts create "${PROJ}-${FUNC}" \
+    --project "${PROJ}"
 
 echo "Saving key for service account..." >&2
 mkdir -p "secrets/test"
 gcloud iam service-accounts keys create "secrets/test/service-account-${FUNC}.json" \
-    --iam-account "gws-noticeboard-${FUNC}@gws-noticeboard.iam.gserviceaccount.com" \
-    --project "gws-noticeboard"
+    --iam-account "${PROJ}-${FUNC}@${PROJ}.iam.gserviceaccount.com" \
+    --project "${PROJ}"
     
 echo "Done." >&2
 
diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -12,15 +12,23 @@ if [ -z "${SUBDIR}" ] || [ -z "${NAME}" ]; then
     exit 1
 fi
 
+PROJ=$(cat secrets/project)
+
+if [ -z "${PROJ}" ]; then
+    echo "Project not found. Check secrets/project file." >&2
+    exit 1
+fi
+
+
 mkdir -p "${SUBDIR}/${NAME}/secrets/${ENV}"
 cp secrets/${ENV}/* "${SUBDIR}/${NAME}/secrets/${ENV}/"
 
 cd "${SUBDIR}/${NAME}"
 
 echo "Building test container..." >&2
-docker build -f "images/test" -t "gws-noticeboard/test/${SUBDIR}/${NAME}" .
+docker build -f "images/test" -t "${PROJ}/test/${SUBDIR}/${NAME}" .
 
 echo "Running tests..." >&2
-docker run "gws-noticeboard/test/${SUBDIR}/${NAME}"
+docker run "${PROJ}/test/${SUBDIR}/${NAME}"
 
 echo "Done." >&2
diff --git a/bin/test-api b/bin/test-api
--- a/bin/test-api
+++ b/bin/test-api
@@ -1,15 +1,22 @@
 #!/usr/bin/env sh
 set -e
 
+PROJ=$(cat secrets/project)
+
+if [ -z "${PROJ}" ]; then
+    echo "Project not found. Check secrets/project file." >&2
+    exit 1
+fi
+
 mkdir -p "api/secrets/test"
 cp secrets/test/* "api/secrets/test/"
 
 cd ./api
 
 echo "Building test container..." >&2
-docker build -f "images/test" -t "gws-noticeboard/test/api" .
+docker build -f "images/test" -t "${PROJ}/test/api" .
 
 echo "Running tests..." >&2
-docker run "gws-noticeboard/test/api"
+docker run "${PROJ}/test/api"
 
 echo "Done." >&2
