reorg into domain-oriented subdomains + services, e.g. domain/Article/Fetch
Note: see DIARY for more info

Article:
    - reimplement Fetch using command messages
    - move shared stuff to Article/shared
    - Article model: take out url, note
    - update Fetch unit tests

test command and image runs tests in subdomain/service

test-api command and image runs API tests

deploy command: start updating, but we have an issue with shared folders.

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,35 +1,41 @@
 #!/usr/bin/env sh
 set -e
 
-SUBDIR=${1}
-NAME=${2}
-ENV=${3-test}
+SUBDOM=${1}
+SERVICE=${2}
 
-if [ -z "${SUBDIR}" ] || [ -z "${NAME}" ]; then
+if [ -z "${SUBDOM}" ] || [ -z "${SERVICE}" ]; then
     echo "Error: missing parameter(s)." >&2
-    echo "    Usage: ${0} TYPE NAME [ENV]" >&2
-    echo "    Example: ${0} functions myfunction staging"  >&2
+    echo "    Usage: ${0} SUBDOMAIN SERVICE" >&2
+    echo "    Example: ${0} Article MyFunction"  >&2
     exit 1
 fi
 
 PROJ=$(cat secrets/project)
-
 if [ -z "${PROJ}" ]; then
     echo "Project not found. Check secrets/project file." >&2
     exit 1
 fi
 
+DOCKERFILE="images/test"
+if [ ! -f "${DOCKERFILE}" ]; then
+    echo "Error: missing Dockerfile ${DOCKERFILE}" >&2
+    exit 1
+fi
 
-rm -fr "${SUBDIR}/${NAME}/secrets/${ENV}"
-mkdir -p "${SUBDIR}/${NAME}/secrets/${ENV}"
-cp -r secrets/${ENV}/* "${SUBDIR}/${NAME}/secrets/${ENV}/"
+rm -fr "domain/${SUBDOM}/${SERVICE}/secrets"
+mkdir -p "domain/${SUBDOM}/${SERVICE}/secrets/test"
+cp -r secrets/test "domain/${SUBDOM}/${SERVICE}/secrets
 
-cd "${SUBDIR}/${NAME}"
+DOCKERTAG=$( echo "${PROJ}/${SUBDOM}/${SERVICE}/test" | tr "[:upper:]" "[:lower:]" )
 
 echo "Building test container..." >&2
-docker build -f "images/test" -t "${PROJ}/test/${SUBDIR}/${NAME}" .
+docker build -f "${DOCKERFILE}" \
+    -t "${DOCKERTAG}" \
+    --build-arg "service=${SERVICE}" \
+    "domain/${SUBDOM}"
 
 echo "Running tests..." >&2
-docker run "${PROJ}/test/${SUBDIR}/${NAME}"
+docker run "${DOCKERTAG}"
 
 echo "Done." >&2
